version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_ENV=development
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=sundarta_db
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - APP_TIMEZONE=Asia/Kolkata
      - APP_NAME=Sundarta
    depends_on:
      - db
    restart: always
    networks:
      - sundarta_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sundarta_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DB.sql:/docker-entrypoint-initdb.d/DB.sql
    networks:
      - sundarta_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  sundarta_network:
    driver: bridge