version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_ENV=production
    ports:
      - "8081:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/assets/uploads:/var/www/html/public/assets/uploads
      - /var/www/html/vendor
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_USER=sundarta_user
      - DB_PASS=production_password
      - DB_NAME=sundarta_db
      - APP_URL=localhost:8081
      - APP_TIMEZONE=Asia/Kolkata
      - APP_NAME=Sundarta
    networks:
      - sundarta_network

  db:
    environment:
      MYSQL_ROOT_PASSWORD: production_password
      MYSQL_DATABASE: sundarta_db
      MYSQL_USER: sundarta_user
      MYSQL_PASSWORD: production_password
    volumes:
      - db_data_prod:/var/lib/mysql
      - ./DB.sql:/docker-entrypoint-initdb.d/DB.sql
      - ./backups:/backups
    ports:
      - "3308:3306"
    networks:
      - sundarta_network

volumes:
  db_data_prod:

networks:
  sundarta_network:
    driver: bridge 