version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_ENV=production
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/assets/uploads:/var/www/html/public/assets/uploads
      - /var/www/html/vendor
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_USER=sundarta_user
      - DB_PASS=production_password
      - DB_NAME=sundarta_db
      - APP_URL=sundarta.com
      - APP_TIMEZONE=Asia/Kolkata
      - APP_NAME=Sundarta
    networks:
      - sundarta_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  db:
    environment:
      MYSQL_ROOT_PASSWORD: production_password
      MYSQL_DATABASE: sundarta_db
      MYSQL_USER: sundarta_user
      MYSQL_PASSWORD: production_password
    volumes:
      - db_data:/var/lib/mysql
      - ./DB.sql:/docker-entrypoint-initdb.d/DB.sql
      - ./backups:/backups
    networks:
      - sundarta_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - sundarta_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 