services:
  # Web service (PHP application)
  - type: web
    name: sundarta
    env: docker
    repo: https://github.com/dog-broad/Sundarta
    dockerfilePath: docker/Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Kolkata
      - key: APP_NAME
        value: Sundarta
    healthCheckPath: /api/health
